CREATE DATABASE NODEJS_CURSOS 

CREATE TABLE USERS(
  ID VARCHAR(50),
  NAME VARCHAR(255),
  USERNAME VARCHAR(255),
  EMAIL VARCHAR(255),
  PRIMARY KEY(ID)
)


SELECT * FROM USERS

ALTER TABLE USERS 
ADD PASSWORD VARCHAR(50) CHECK(LENGTH(PASSWORD) >= 8)